export type TbhItem = {
  item_key: string;
  item_type: string | null;
  grade: string | null;
  parts: string | null;
  gear_type: string | null;
  gear_group: string | null;
  item_synthesis_type: string | null;
  name_key: string | null;
  description_key: string | null;
  gear_key: string | null;
  drop_key: string | null;
  drop_cooldown: string | null;
  level: string | null;
  is_steam_item: string | null;
  icon_path: string | null;
  is_bucket_box: string | null;
  is_deleted_in_server: string | null;
  is_can_exchange_marketable: string | null;
  is_temp_marketable_false: string | null;
  name_pt_br: string | null;
  name_en_us: string | null;
  description_pt_br: string | null;
  description_en_us: string | null;
};

export type TbhStage = {
  stage_key: string;
  stage_name_key: string | null;
  stage_type: string | null;
  stage_difficulty: string | null;
  act: string | null;
  stage_no: string | null;
  stage_level: string | null;
  next_stage_key: string | null;
  wave_amount: string | null;
  wave_monster_amount: string | null;
  monsters: string | null;
  monster_drop_item_key: string | null;
  monster_drop_item_rate: string | null;
  boss_drop_item_key: string | null;
  boss_drop_item_rate: string | null;
  first_clear_drop_key: string | null;
  boss_monster_key: string | null;
  boss_damage_multiplier: string | null;
  boss_hp_multiplier: string | null;
  boss_gold_multiplier: string | null;
  boss_exp_multiplier: string | null;
  boss_scale: string | null;
  soulstone_item_key: string | null;
  soulstone_amount: string | null;
  is_demo: string | null;
  bgm_sound_key: string | null;
  name_pt_br: string | null;
  name_en_us: string | null;
};

export type TbhDrop = {
  id: number;
  stage_key: string | null;
  stage_name_pt_br: string | null;
  stage_name_en_us: string | null;
  act: string | null;
  stage_no: string | null;
  stage_level: string | null;
  stage_type: string | null;
  source_type: string | null;
  source_item_key: string | null;
  source_item_name_pt_br: string | null;
  source_rate: string | null;
  drop_key: string | null;
  drop_type: string | null;
  reward_type: string | null;
  reward_key: string | null;
  hero_key_condition: string | null;
  weight: string | null;
  weight_percent_within_dropkey: number | null;
  resolved_item_key: string | null;
  resolved_from_group_key: string | null;
  item_name_pt_br: string | null;
  item_name_en_us: string | null;
  item_type: string | null;
  grade: string | null;
  level: string | null;
  gear_type: string | null;
  parts: string | null;
};

export type TbhMarketItem = TbhItem & {
  market_hash_name: string | null;
  market_enabled: boolean | null;
  appid: number | null;
  currency: number | null;
  price_success: boolean | null;
  lowest_price_text: string | null;
  median_price_text: string | null;
  volume: string | null;
  lowest_price_brl: number | null;
  median_price_brl: number | null;
  last_error: string | null;
  last_success_at: string | null;
  price_updated_at: string | null;
  drop_count: number | null;
  max_drop_weight_percent: number | null;
  avg_drop_weight_percent: number | null;
  rarity_score: number | null;
  market_score: number | null;
  cost_benefit_score: number | null;
  opportunity_score: number | null;
};

export type TbhFarmMarketStage = {
  stage_key: string | null;
  stage_name_pt_br: string | null;
  stage_name_en_us: string | null;
  act: string | null;
  stage_no: string | null;
  stage_level: string | null;
  stage_type: string | null;
  source_type: string | null;
  drop_items_count: number | null;
  priced_items_count: number | null;
  estimated_value_brl: number | null;
  best_single_price_brl: number | null;
  avg_priced_item_brl: number | null;
  best_market_score: number | null;
  avg_market_score: number | null;
  best_item_name_pt_br: string | null;
};
